apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: my-cluster
spec:
  kafka:
    # version: 3.0.0
    version: 2.8.1
    replicas: 3
    listeners:
      - name: plain
        port: 9092
        type: nodeport
        tls: false
        configuration:
          bootstrap:
            nodePort: 32100
          brokers:
          - broker: 0
            nodePort: 32000
            advertisedHost: 192.168.49.2
            advertisedPort: 32000
          - broker: 1
            nodePort: 32001
            advertisedHost: 192.168.49.2
            advertisedPort: 32001
          - broker: 2
            nodePort: 32002
            advertisedHost: 192.168.49.2
            advertisedPort: 32002
    config:
      offsets.topic.replication.factor: 3
      transaction.state.log.replication.factor: 3
      transaction.state.log.min.isr: 2
      # log.message.format.version: "3.0"
      # inter.broker.protocol.version: "3.0"
    storage:
      type: jbod
      volumes:
      - id: 0
        type: persistent-claim
        size: 10Gi
        deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 10Gi
      deleteClaim: false
  cruiseControl: {}
  entityOperator:
    topicOperator: {}
    userOperator: {}

