apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: pod-failure-example
  namespace: default
spec:
  action: pod-failure
  mode: all
  duration: '30s'
  selector:
    labelSelectors:
      'app.kubernetes.io/name': 'kafka'

